version: "2"
services:
    users:
        image: playlist-grpc
        expose:
            - 8083
        labels:
            project.git: "github.com/kostyasolovev/playlist-grpc"    # ссылка на репозиторий
            project.git.branch: main       # нужный бранч, по умолчанию - мастер
            project.build: make                          # добавляем команду для сборки имиджа

    web-ui:
        image: playlist-server
        expose:
          - 8083
        ports:
            - 8081:8081
        labels:
            project.git: "github.com/kostyasolovev/playlist-server"
            project.build: make